const CAFES = [
  {
    id: 'third-wave-indiranagar',
    name: 'Third Wave Coffee',
    short: 'Third Wave',
    area: 'Indiranagar',
    address: '4th Main Rd, HAL 2nd Stage, Indiranagar',
    lat: 12.9719, lng: 77.6412,
    rating: 4.5, reviews: 1240,
    priceRange: '₹₹',
    hours: '7:00 am – 11:00 pm',
    tags: ['Specialty', 'Work-friendly', 'Wi-Fi'],
    vibe: 'Bright, airy pour-over bar with long communal tables. A go-to for remote workers and coffee purists.',
    mustTry: 'Ethiopian Pour Over, Cold Brew Tonic',
    ig: '@thirdwavecoffee',
    igUrl: 'https://www.instagram.com/thirdwavecoffee/',
    mapsQuery: 'Third Wave Coffee Indiranagar Bengaluru',
    artColor: '#4D7C52', artBg: '#EBF3E8', artPattern: 0,
    isNew: false, isTrending: true,
    types: ['specialty', 'work'],
  },
  {
    id: 'blue-tokai-koramangala',
    name: 'Blue Tokai Coffee Roasters',
    short: 'Blue Tokai',
    area: 'Koramangala',
    address: '5th Block, Koramangala',
    lat: 12.9352, lng: 77.6245,
    rating: 4.7, reviews: 2100,
    priceRange: '₹₹',
    hours: '8:00 am – 10:00 pm',
    tags: ['Roastery', 'Specialty', 'Single Origin'],
    vibe: "India's favourite specialty roastery. Clean minimal space with direct-trade beans from across the country.",
    mustTry: 'Vienna Coffee, Araku Espresso, Flat White',
    ig: '@bluetokaicoffee',
    igUrl: 'https://www.instagram.com/bluetokaicoffee/',
    mapsQuery: 'Blue Tokai Coffee Roasters Koramangala Bengaluru',
    artColor: '#1D9E75', artBg: '#E1F5EE', artPattern: 1,
    isNew: false, isTrending: true,
    types: ['specialty', 'roastery'],
  },
  {
    id: 'matteo-coffea-mgroad',
    name: 'Matteo Coffea',
    short: 'Matteo',
    area: 'MG Road',
    address: 'St. Marks Road, near MG Road Metro',
    lat: 12.9757, lng: 77.6011,
    rating: 4.4, reviews: 890,
    priceRange: '₹₹',
    hours: '9:00 am – 10:30 pm',
    tags: ['Cozy', 'Desserts', 'Instagrammable'],
    vibe: 'Warm wooden interiors, great cakes, and exceptional espresso. A calm island in the heart of the city.',
    mustTry: 'Hazelnut Latte, Belgian Waffle, Cortado',
    ig: '@matteocoffea',
    igUrl: 'https://www.instagram.com/matteocoffea/',
    mapsQuery: 'Matteo Coffea MG Road Bengaluru',
    artColor: '#BA7517', artBg: '#FAEEDA', artPattern: 2,
    isNew: false, isTrending: false,
    types: ['specialty'],
  },
  {
    id: 'corridor-coffee-koramangala',
    name: 'Corridor Coffee',
    short: 'Corridor',
    area: 'Koramangala 5th Block',
    address: '5th Block, Koramangala',
    lat: 12.9288, lng: 77.6273,
    rating: 4.3, reviews: 560,
    priceRange: '₹',
    hours: '8:30 am – 9:30 pm',
    tags: ['Minimalist', 'Quiet', 'Work-friendly'],
    vibe: 'Hushed, no-frills cafe tucked in an industrial corridor. Exceptional brews with zero distractions.',
    mustTry: 'Filter Kaapi, Black Americano',
    ig: '@corridorcoffee',
    igUrl: 'https://www.instagram.com/corridorcoffee/',
    mapsQuery: 'Corridor Coffee Koramangala Bengaluru',
    artColor: '#D85A30', artBg: '#FAECE7', artPattern: 3,
    isNew: false, isTrending: false,
    types: ['work', 'specialty', 'filter-coffee'],
  },
  {
    id: 'araku-koramangala',
    name: 'Araku Coffee',
    short: 'Araku',
    area: 'Koramangala',
    address: 'Koramangala, Bengaluru',
    lat: 12.9359, lng: 77.6199,
    rating: 4.6, reviews: 740,
    priceRange: '₹₹₹',
    hours: '8:00 am – 10:00 pm',
    tags: ['Single Origin', 'Award-winning', 'Specialty'],
    vibe: 'From the Araku Valley forests to your cup. Award-winning tribal-grown coffee, beautifully presented.',
    mustTry: 'Araku Cold Brew, Honey Process Espresso',
    ig: '@araku.world',
    igUrl: 'https://www.instagram.com/araku.world/',
    mapsQuery: 'Araku Coffee Koramangala Bengaluru',
    artColor: '#639922', artBg: '#EAF3DE', artPattern: 4,
    isNew: false, isTrending: true,
    types: ['specialty', 'roastery'],
  },
  {
    id: 'flying-squirrel-indiranagar',
    name: 'The Flying Squirrel',
    short: 'Flying Squirrel',
    area: 'Indiranagar',
    address: '100 Feet Road, Indiranagar',
    lat: 12.9736, lng: 77.6429,
    rating: 4.4, reviews: 1050,
    priceRange: '₹₹',
    hours: '8:00 am – 10:00 pm',
    tags: ['Estate Coffee', 'Roastery', 'Specialty'],
    vibe: 'Coorg estate-backed roastery with beautiful light-filled interiors. Every cup tells a story of origin.',
    mustTry: 'Estate Espresso, Natural Process Filter',
    ig: '@flyingsquirrelcoffee',
    igUrl: 'https://www.instagram.com/flyingsquirrelcoffee/',
    mapsQuery: 'Flying Squirrel Coffee Indiranagar Bengaluru',
    artColor: '#534AB7', artBg: '#EEEDFE', artPattern: 0,
    isNew: false, isTrending: false,
    types: ['specialty', 'roastery'],
  },
  {
    id: 'subko-sadashivanagar',
    name: 'Subko Coffee',
    short: 'Subko',
    area: 'Sadashivanagar',
    address: 'Sadashivanagar, Bengaluru',
    lat: 12.9987, lng: 77.5768,
    rating: 4.5, reviews: 430,
    priceRange: '₹₹₹',
    hours: '9:00 am – 9:00 pm',
    tags: ['Specialty', 'Minimalist', 'Quiet'],
    vibe: "Mumbai's cult specialty brand in Bengaluru. Precision brewing in a gallery-like space — every detail intentional.",
    mustTry: 'Oat Milk Flat White, Signature Cold Brew',
    ig: '@subkocoffee',
    igUrl: 'https://www.instagram.com/subkocoffee/',
    mapsQuery: 'Subko Coffee Sadashivanagar Bengaluru',
    artColor: '#D4537E', artBg: '#FBEAF0', artPattern: 1,
    isNew: true, isTrending: true,
    types: ['specialty'],
  },
  {
    id: 'hatti-kaapi',
    name: 'Hatti Kaapi',
    short: 'Hatti Kaapi',
    area: 'Multiple locations',
    address: 'Indiranagar, Koramangala, Jayanagar & more',
    lat: 12.9342, lng: 77.6183,
    rating: 4.2, reviews: 3400,
    priceRange: '₹',
    hours: '7:00 am – 10:00 pm',
    tags: ['Traditional', 'Filter Coffee', 'Affordable'],
    vibe: 'Authentic South Indian filter kaapi done right. Standing-room decoction counters, quick service, soul-warming cups.',
    mustTry: 'Filter Kaapi, Masala Chai, Idli',
    ig: '@hattikaapi',
    igUrl: 'https://www.instagram.com/hattikaapi/',
    mapsQuery: 'Hatti Kaapi Bengaluru',
    artColor: '#888780', artBg: '#F1EFE8', artPattern: 2,
    isNew: false, isTrending: false,
    types: ['filter-coffee'],
  },
  {
    id: 'kapi-katha-jpnagar',
    name: 'Kapi Katha',
    short: 'Kapi Katha',
    area: 'JP Nagar',
    address: 'JP Nagar 7th Phase, Bengaluru',
    lat: 12.9121, lng: 77.5820,
    rating: 4.3, reviews: 310,
    priceRange: '₹₹',
    hours: '8:30 am – 9:30 pm',
    tags: ['Cozy', 'Outdoor seating', 'Filter Coffee'],
    vibe: 'A quiet neighbourhood gem with a courtyard garden. Unhurried, warm, quintessentially Bengaluru.',
    mustTry: 'Filter Kaapi, Cold Brew, Benne Masala Dosa',
    ig: '@kapikatha',
    igUrl: 'https://www.instagram.com/kapikatha/',
    mapsQuery: 'Kapi Katha JP Nagar Bengaluru',
    artColor: '#4D7C52', artBg: '#EBF3E8', artPattern: 3,
    isNew: false, isTrending: false,
    types: ['filter-coffee', 'outdoor'],
  },
  {
    id: 'bloom-bean-hsr',
    name: 'Bloom & Bean',
    short: 'Bloom & Bean',
    area: 'HSR Layout',
    address: 'HSR Layout Sector 1, Bengaluru',
    lat: 12.9099, lng: 77.6385,
    rating: 4.4, reviews: 290,
    priceRange: '₹₹',
    hours: '8:00 am – 10:00 pm',
    tags: ['Matcha', 'Specialty', 'Outdoor', 'Pet-friendly'],
    vibe: 'Sunlit courtyard cafe with serious matcha and excellent beans. Garden seating, pet-friendly, very Insta-worthy.',
    mustTry: 'Iced Matcha Latte, Ethiopian V60, Avocado Toast',
    ig: '@bloomandbean.blr',
    igUrl: 'https://www.instagram.com/',
    mapsQuery: 'Bloom and Bean HSR Layout Bengaluru',
    artColor: '#4D7C52', artBg: '#EBF3E8', artPattern: 4,
    isNew: true, isTrending: false,
    types: ['specialty', 'matcha', 'outdoor'],
  },
];
